git clone https://github.com/Emily311/folder-poetry-emily.git && \
git clone https://github.com/KaiwenChen0905/folder-poetry-kevin.git && \
git clone https://github.com/ksm492/folder-poetry-kiana.git && \
git clone https://github.com/katrinamber/folder-poetry-katrina.git && \
git clone https://github.com/yanxinnn/folder-poetry-yanxin.git && \
git clone https://github.com/ql1019/folder-poetry-martin.git && \
git clone https://github.com/IreneeL/folder-poetry-irene.git && \
git clone https://github.com/Estherpyr/folder-poetry-esther.git && \
git clone https://github.com/Karl-Woo/folder-poetry-karl.git && \
git clone https://github.com/franthecrayon/folder-poetry-francesca.git && \
git clone https://github.com/carolinemche/folderpoetry-caroline.git && \
git clone https://github.com/sammylevin10/folder-poetry-sammy.git && \
git clone https://github.com/mittymild/folder-poetry-prismo.git && \
git clone https://github.com/fionanicole/folder-poetry-fiona.git && \
git clone https://github.com/Tyarporn/folder-poetry-ty.git && \
git clone https://github.com/simbayona/folder-poetry-simon.git && \
git clone https://github.com/ashlib/folder-poetry-ashli.git && \
git clone https://github.com/alishapdhir/folder-poetry-Alisha.git && \
git clone https://github.com/fc1499/folder-poetry-frederic.git && \
git clone https://github.com/zhumingcheng697/folder-poetry-mccoy.git 
